# openapi2-run.yaml
swagger: '2.0'
info:
  title: SudokuMain-fastapi "Backend API for Flutter Sudoku application"
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
securityDefinitions:
    # This section configures basic authentication with an API Key.
    api_key:
      type: "apiKey"
      name: "key"
      in: "query"
paths:
  /assets/{asset}:
    get:
      parameters:
        - in: path
          name: asset
          type: string
          required: true
          description: Name of the asset.
      summary: Assets
      operationId: getAsset
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /hello:
    get:
      summary: Cloud Run hello world
      operationId: hello
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /docs: 
    #GET Http method   
    get:                               
      summary: Greet two user by their names.
      # parameters:
      #     - in: "header"
      #       name: "x-api-key"
      #       required: true
      #       type: string
      operationId: hello_users
      #actual address of the cloud function where the request is supposed to be forwarded
      x-google-backend:             
        address: ${base}/docs
      #authenticate with api_key query param
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string 
  /openapi.json:    
    get:
      summary: Overall definition of avaible APIs
      operationId: openapijson
      #actual address of the cloud function where the request is supposed to be forwarded
      x-google-backend:
        address: ${base}/openapi.json
      #authenticate with api_key query param
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  # /api/v2/public/highscores/:
  #   get:
  #     summary: Public Highscore
  #     operationId: public_highscore_me_api_v2_public_highscores__me__get
  #     x-google-backend:             
  #       address: ${base}/api/v2/public/highscores/
  #     security:
  #       - api_key: []
  #     responses:
  #       '200':
  #         description: Successful Response
  #         schema:
  #           type: string

